=== YuriyGorvitovskiy/record-dom-mapper/lib/src/test/resources/io/openmapper/recordxml/v5/Polymorphic.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Test" type="TypeOf_DerivedC"/>
    <xs:complexType name="TypeOf_DerivedC_Field_recursive">
        <xs:choice minOccurs="0">
            <xs:element name="DerivedA" type="TypeOf_DerivedA"/>
            <xs:element name="DerivedB" type="TypeOf_DerivedB"/>
            <xs:element name="DerivedC" type="TypeOf_DerivedC"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TypeOf_DerivedA">
        <xs:sequence>
            <xs:choice minOccurs="0">
                <xs:element name="DerivedA" type="TypeOf_DerivedA"/>
                <xs:element name="DerivedB" type="TypeOf_DerivedB"/>
                <xs:element name="DerivedC" type="TypeOf_DerivedC"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TypeOf_DerivedB">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="DerivedA" type="EntryOf_DerivedA_By_string"/>
                <xs:element name="DerivedB" type="EntryOf_DerivedB_By_string"/>
                <xs:element name="DerivedC" type="EntryOf_DerivedC_By_string"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="EntryOf_DerivedA_By_string">
        <xs:complexContent>
            <xs:extension base="TypeOf_DerivedA">
                <xs:attribute name="Key" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EntryOf_DerivedB_By_string">
        <xs:complexContent>
            <xs:extension base="TypeOf_DerivedB">
                <xs:attribute name="Key" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="EntryOf_DerivedC_By_string">
        <xs:complexContent>
            <xs:extension base="TypeOf_DerivedC">
                <xs:attribute name="Key" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MapOf_Base_By_string">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="DerivedA" type="EntryOf_DerivedA_By_string"/>
            <xs:element name="DerivedB" type="EntryOf_DerivedB_By_string"/>
            <xs:element name="DerivedC" type="EntryOf_DerivedC_By_string"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TypeOf_DerivedC">
        <xs:sequence>
            <xs:element minOccurs="0" name="recursive" type="TypeOf_DerivedC_Field_recursive"/>
            <xs:element minOccurs="0" name="recursiveMap" type="MapOf_Base_By_string"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== YuriyGorvitovskiy/record-dom-mapper/lib/src/test/resources/io/openmapper/recordxml/v5/Polymorphic.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="1" xsi:noNamespaceSchemaLocation="./Polymorphic.xsd">
    <recursive>
        <DerivedA name="S1">
            <DerivedB name="S1-1"/>
        </DerivedA>
    </recursive>
    <recursiveMap>
        <DerivedB Key="one" name="P1">
            <DerivedA Key="one" name="P1-1"/>
            <DerivedB Key="two" name="P1-2">
                <DerivedA Key="one" name="P1-2-1"/>
                <DerivedB Key="two" name="P1-2-2"/>
                <DerivedC Key="three"/>
            </DerivedB>
            <DerivedC Key="three" name="P1-3">
                <recursive>
                    <DerivedB name="P1-3-S1"/>
                </recursive>
                <recursiveMap>
                    <DerivedA Key="one" name="P1-3-P1"/>
                </recursiveMap>
            </DerivedC>
        </DerivedB>
        <DerivedC Key="two" name="P2"/>
        <DerivedA Key="three" name="P3">
            <DerivedC name="P3-1"/>
        </DerivedA>
    </recursiveMap>
</Test>
